import { ReactChild } from 'react'
import { Container } from '@material-ui/core'
import Head from 'next/head'
import { Navigation } from './navigation'
import { useLayoutStyles } from './styles'
import { ErrorBoundary } from '../error-boundary'

type PageLayout = {
  children?: ReactChild
}

export const PageLayout = (props: PageLayout) => {
  const { children } = props

  const layoutStyles = useLayoutStyles()

  return (
    <Container maxWidth='md' className={layoutStyles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navigation />

      <main className={layoutStyles.main}>
        <ErrorBoundary>{children}</ErrorBoundary>
      </main>
    </Container>
  )
}

export default PageLayout
